version: "3.9"

services:
  # 1) 데이터베이스 ------------------------------------------------------------------
  db:
    image: mariadb:10.11
    container_name: db
    volumes:
      # 로컬 볼륨 → 컨테이너 내부의 DB 데이터 디렉터리로 마운트
      - dev-db-data:/var/lib/mysql          # 공식 이미지 기준 경로
    environment:
      # 꼭 실제 비밀값으로 교체하세요
      MARIADB_ROOT_PASSWORD: some_root_password
      MARIADB_DATABASE: devdb
      MARIADB_USER: devuser
      MARIADB_PASSWORD: changeme
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psome_root_password"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      custom-net:

  # 2) 캐시 / 메시지브로커 ------------------------------------------------------------
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      custom-net:

  # 3) 백엔드(Spring Boot + Gradle) ---------------------------------------------------
  app:
    image: my-backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # 백엔드가 내부 네트워크 컨테이너 이름으로 DB·Redis에 붙도록 설정
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/devdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: changeme
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    expose:
      - "8080"
    networks:
      custom-net:
        ipv4_address: 192.168.48.4

  # 4) 프론트엔드(React + Vite → Nginx 멀티스테이지) ----------------------------------
  frontend:
    image: my-frontend
    container_name: frontend
    depends_on:
      - app                       # 백엔드 뜬 뒤 실행
    environment:
      # 필요하면 API 주소를 환경변수로 주입 (Vite + Nginx 기준 예시)
      VITE_API_BASE_URL: http://backend:8080
    expose:
      - "80"
    networks:
      custom-net:
        ipv4_address: 192.168.48.5

volumes:
  dev-db-data:

networks:
  custom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.48.0/24
